const LABELS: Record<string, string> = {
  DRAFT: "پیش‌نویس",
  SUBMITTED: "ارسال‌شده",
  UNDER_REVIEW: "در بررسی",
  PUBLISHED: "منتشرشده",
  MATCHING: "در حال تطبیق",
  SUPPLIER_RESPONDED: "پاسخ تأمین‌کننده",
  OFFER_ACCEPTED: "پیشنهاد پذیرفته",
  CANCELLED: "لغو شده",
  REJECTED: "رد شده",
  ACCEPTED: "پذیرفته",
  ACTIVE: "فعال",
  APPROVED: "تأیید شده",
  BLOCKED: "مسدود",
  DEACTIVATED: "غیرفعال",
  PENDING_VERIFICATION: "در انتظار احراز",
  OFFERED_TO_DRIVERS: "اعلام به رانندگان",
  DRIVER_APPLIED: "اعلام آمادگی راننده",
  DRIVER_SELECTED: "راننده انتخاب شد",
  DRIVER_ASSIGNED: "راننده تخصیص یافت",
  ARRIVING_AT_PICKUP: "در مسیر بارگیری",
  AT_PICKUP: "در محل بارگیری",
  LOADING: "در حال بارگیری",
  LOADED: "بارگیری شد",
  IN_TRANSIT: "در مسیر",
  ARRIVING_AT_DESTINATION: "نزدیک مقصد",
  AT_DESTINATION: "در مقصد",
  UNLOADING: "تخلیه",
  DELIVERED: "تحویل شد",
  PROOF_SUBMITTED: "رسید ثبت شد",
  COMPLETED: "تکمیل شده",
  DISPUTED: "اختلاف",
  PLATFORM: "سامانه",
  REQUESTER: "صاحب بار",
  SUPPLIER: "شرکت پخش",
  TRANSPORT_PENDING: "در انتظار راننده",
  TRANSPORT_ASSIGNED: "راننده تخصیص یافت",
  PICKUP_SCHEDULED: "زمان بارگیری ثبت شد",
  ISSUED: "صادر شده",
  TRANSPORT: "حمل",
  DRIVER: "راننده",
  CARRIER: "حمل‌کننده",
  VAN: "وانت سبک",
  LIGHT_TRUCK: "وانت سنگین",
  TRUCK: "کامیون",
  HEAVY_TRUCK: "تریلی سبک",
  TRAILER: "تریلی",
  CONTAINER: "کانتینر",
  REFRIGERATED: "یخچال‌دار",
  TANKER: "تانکر",
  FLATBED: "کفی",
  CONNECTED: "متصل",
  DISCONNECTED: "قطع‌شده",
  TOPUP: "شارژ",
  INCOME: "درآمد",
  VEHICLE_EXPENSE: "هزینه ماشین",
  TRAVEL_EXPENSE: "رفت‌وآمد",
  WITHDRAW: "برداشت",
  PAID: "تسویه شده",
  PARTIALLY_PAID: "تسویه ناقص",
  OVERDUE: "سررسید گذشته",
  VOID: "باطل",
  SENT: "ارسال‌شده",
  ADJUSTMENT: "اصلاحیه",
  COMMISSION: "کارمزد",
  OPEN: "باز",
  IN_PROGRESS: "در حال پیگیری",
  WAITING_FOR_USER: "در انتظار پاسخ",
  WAITING_FOR_INFORMATION: "در انتظار مدرک",
  RESOLVED: "حل‌شده",
  CLOSED: "بسته",
  DAMAGE: "آسیب بار",
  SHORTAGE: "کسری کالا",
  DELAY: "تأخیر",
  OVERCHARGE: "هزینه اضافه",
  NO_SHOW: "عدم حضور",
  OTHER: "سایر",
  BILLING: "مالی و فاکتور",
  LOAD: "بار و حمل",
  ACCOUNT: "حساب کاربری",
  TRACKING: "ردیابی",
  LOW: "کم",
  MEDIUM: "متوسط",
  HIGH: "زیاد",
  URGENT: "فوری",
};

export function statusFa(status?: string | null) {
  if (!status) return "—";
  return LABELS[status] ?? status;
}
