export const PERMISSIONS = [
  "users.read",
  "users.create",
  "users.update",
  "users.suspend",
  "users.impersonate",
  "users.export",
  "roles.read",
  "roles.manage",
  "companies.read",
  "companies.create",
  "companies.update",
  "companies.verify",
  "companies.reject",
  "companies.suspend",
  "stores.read",
  "stores.create",
  "stores.update",
  "warehouses.read",
  "warehouses.create",
  "warehouses.update",
  "suppliers.read",
  "suppliers.update",
  "suppliers.verify",
  "suppliers.reject",
  "supplier_products.manage",
  "supplier_capacity.manage",
  "drivers.read",
  "drivers.update",
  "drivers.verify",
  "drivers.reject",
  "carriers.read",
  "carriers.verify",
  "vehicles.read",
  "vehicles.manage",
  "products.read",
  "products.manage",
  "categories.manage",
  "requests.read",
  "requests.create",
  "requests.update",
  "requests.publish",
  "requests.cancel",
  "requests.review",
  "marketplace.supplier.read",
  "marketplace.driver.read",
  "offers.read",
  "offers.create",
  "offers.update",
  "offers.accept",
  "offers.reject",
  "offers.withdraw",
  "orders.read",
  "orders.update",
  "orders.cancel",
  "jobs.read",
  "jobs.apply",
  "jobs.assign",
  "jobs.confirm",
  "jobs.update_status",
  "jobs.cancel",
  "shipments.read",
  "shipments.update",
  "invoices.read",
  "invoices.manage",
  "payments.read",
  "payments.manage",
  "wallet.read",
  "wallet.manage",
  "commissions.read",
  "commissions.manage",
  "settlements.read",
  "settlements.manage",
  "documents.read",
  "documents.upload",
  "documents.verify",
  "documents.delete",
  "notifications.read",
  "notifications.manage",
  "messages.read",
  "messages.send",
  "tickets.read",
  "tickets.create",
  "tickets.manage",
  "ratings.read",
  "ratings.create",
  "disputes.read",
  "disputes.create",
  "disputes.manage",
  "reports.read",
  "analytics.read",
  "audit_logs.read",
  "settings.read",
  "settings.manage",
  "business_rules.manage",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const SYSTEM_ROLES: Record<
  string,
  { name: string; portal: "PLATFORM" | "REQUESTER" | "SUPPLIER" | "DRIVER" | "CARRIER"; permissions: PermissionCode[] }
> = {
  SUPER_ADMIN: { name: "Super admin", portal: "PLATFORM", permissions: [...PERMISSIONS] },
  ADMIN: {
    name: "Admin",
    portal: "PLATFORM",
    permissions: PERMISSIONS.filter((p) => p !== "users.impersonate" && p !== "roles.manage"),
  },
  PROCUREMENT_MANAGER: {
    name: "Procurement manager",
    portal: "PLATFORM",
    permissions: [
      "companies.read",
      "stores.read",
      "warehouses.read",
      "suppliers.read",
      "products.read",
      "products.manage",
      "categories.manage",
      "requests.read",
      "requests.update",
      "requests.publish",
      "requests.cancel",
      "requests.review",
      "offers.read",
      "offers.accept",
      "offers.reject",
      "orders.read",
      "analytics.read",
      "reports.read",
    ],
  },
  LOGISTICS_MANAGER: {
    name: "Logistics manager",
    portal: "PLATFORM",
    permissions: [
      "drivers.read",
      "drivers.update",
      "carriers.read",
      "vehicles.read",
      "vehicles.manage",
      "jobs.read",
      "jobs.assign",
      "jobs.confirm",
      "jobs.update_status",
      "jobs.cancel",
      "shipments.read",
      "shipments.update",
      "orders.read",
      "analytics.read",
      "reports.read",
    ],
  },
  FINANCE_MANAGER: {
    name: "Finance manager",
    portal: "PLATFORM",
    permissions: [
      "invoices.read",
      "invoices.manage",
      "payments.read",
      "payments.manage",
      "commissions.read",
      "commissions.manage",
      "settlements.read",
      "settlements.manage",
      "orders.read",
      "reports.read",
    ],
  },
  SUPPORT_AGENT: {
    name: "Support agent",
    portal: "PLATFORM",
    permissions: [
      "users.read",
      "companies.read",
      "orders.read",
      "requests.read",
      "shipments.read",
      "tickets.read",
      "tickets.manage",
      "messages.read",
      "messages.send",
      "disputes.read",
      "disputes.manage",
    ],
  },
  VERIFICATION_AGENT: {
    name: "Verification agent",
    portal: "PLATFORM",
    permissions: [
      "users.read",
      "companies.read",
      "companies.verify",
      "companies.reject",
      "suppliers.read",
      "suppliers.verify",
      "suppliers.reject",
      "drivers.read",
      "drivers.verify",
      "drivers.reject",
      "carriers.read",
      "carriers.verify",
      "documents.read",
      "documents.verify",
      "documents.upload",
    ],
  },
  ANALYST: {
    name: "Analyst",
    portal: "PLATFORM",
    permissions: ["analytics.read", "reports.read", "audit_logs.read", "orders.read", "requests.read"],
  },
  REQUESTER_OWNER: {
    name: "Requester owner",
    portal: "REQUESTER",
    permissions: [
      "stores.read",
      "stores.create",
      "stores.update",
      "warehouses.read",
      "warehouses.create",
      "warehouses.update",
      "requests.read",
      "requests.create",
      "requests.update",
      "requests.cancel",
      "offers.read",
      "offers.accept",
      "offers.reject",
      "orders.read",
      "orders.cancel",
      "jobs.read",
      "jobs.assign",
      "jobs.confirm",
      "shipments.read",
      "documents.read",
      "documents.upload",
      "invoices.read",
      "messages.read",
      "messages.send",
      "tickets.create",
      "tickets.read",
      "ratings.create",
      "disputes.create",
      "disputes.read",
      "reports.read",
    ],
  },
  SUPPLIER_OWNER: {
    name: "Supplier owner",
    portal: "SUPPLIER",
    permissions: [
      "supplier_products.manage",
      "supplier_capacity.manage",
      "marketplace.supplier.read",
      "offers.read",
      "offers.create",
      "offers.update",
      "offers.withdraw",
      "orders.read",
      "jobs.read",
      "jobs.assign",
      "jobs.confirm",
      "shipments.read",
      "documents.read",
      "documents.upload",
      "invoices.read",
      "messages.read",
      "messages.send",
      "ratings.create",
      "disputes.create",
      "disputes.read",
      "reports.read",
    ],
  },
  DRIVER: {
    name: "Driver",
    portal: "DRIVER",
    permissions: [
      "marketplace.driver.read",
      "jobs.read",
      "jobs.apply",
      "jobs.update_status",
      "shipments.read",
      "shipments.update",
      "documents.upload",
      "documents.read",
      "messages.read",
      "messages.send",
      "ratings.create",
      "disputes.create",
      "disputes.read",
      "tickets.create",
      "tickets.read",
      "reports.read",
      "wallet.read",
      "wallet.manage",
    ],
  },
};

export function hasPermission(permissions: Set<string>, isSuperAdmin: boolean, code: string) {
  if (isSuperAdmin) return true;
  return permissions.has(code);
}
