import type {
  OfferStatus,
  OrderStatus,
  RequestStatus,
  TransportJobStatus,
  DisputeStatus,
  InvoiceStatus,
  PaymentStatus,
} from "@prisma/client";
import { Errors } from "@/server/errors";

export const REQUEST_TRANSITIONS: Record<RequestStatus, RequestStatus[]> = {
  DRAFT: ["SUBMITTED", "CANCELLED"],
  SUBMITTED: ["UNDER_REVIEW", "PUBLISHED", "CANCELLED"],
  UNDER_REVIEW: ["PUBLISHED", "CANCELLED"],
  PUBLISHED: ["MATCHING", "CANCELLED"],
  MATCHING: ["SUPPLIER_RESPONDED", "CANCELLED", "DISPUTED"],
  SUPPLIER_RESPONDED: ["SUPPLIER_SELECTED", "MATCHING", "CANCELLED", "DISPUTED"],
  SUPPLIER_SELECTED: ["TRANSPORT_PENDING", "CANCELLED", "DISPUTED"],
  TRANSPORT_PENDING: ["TRANSPORT_ASSIGNED", "CANCELLED", "DISPUTED"],
  TRANSPORT_ASSIGNED: ["PICKUP_SCHEDULED", "CANCELLED", "DISPUTED"],
  PICKUP_SCHEDULED: ["IN_TRANSIT", "CANCELLED", "DISPUTED"],
  IN_TRANSIT: ["DELIVERED", "DISPUTED", "CANCELLED"],
  DELIVERED: ["RECEIVED", "DISPUTED"],
  RECEIVED: ["COMPLETED", "DISPUTED"],
  COMPLETED: [],
  CANCELLED: [],
  DISPUTED: ["MATCHING", "TRANSPORT_PENDING", "IN_TRANSIT", "CANCELLED", "COMPLETED"],
};

export const OFFER_TRANSITIONS: Record<OfferStatus, OfferStatus[]> = {
  DRAFT: ["SUBMITTED", "CANCELLED"],
  SUBMITTED: ["UNDER_REVIEW", "ACCEPTED", "REJECTED", "EXPIRED", "WITHDRAWN", "CANCELLED"],
  UNDER_REVIEW: ["ACCEPTED", "REJECTED", "EXPIRED", "CANCELLED"],
  ACCEPTED: ["CANCELLED"],
  REJECTED: [],
  EXPIRED: [],
  CANCELLED: [],
  WITHDRAWN: [],
};

export const ORDER_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  CREATED: ["CONFIRMED", "CANCELLED"],
  CONFIRMED: ["AWAITING_TRANSPORT", "CANCELLED", "DISPUTED"],
  AWAITING_TRANSPORT: ["IN_FULFILLMENT", "CANCELLED", "DISPUTED"],
  IN_FULFILLMENT: ["PARTIALLY_FULFILLED", "DELIVERED", "DISPUTED", "CANCELLED"],
  PARTIALLY_FULFILLED: ["DELIVERED", "COMPLETED", "DISPUTED", "CANCELLED"],
  DELIVERED: ["COMPLETED", "DISPUTED"],
  COMPLETED: [],
  CANCELLED: [],
  DISPUTED: ["IN_FULFILLMENT", "CANCELLED", "COMPLETED"],
};

export const JOB_TRANSITIONS: Record<TransportJobStatus, TransportJobStatus[]> = {
  CREATED: ["MATCHING", "CANCELLED"],
  MATCHING: ["OFFERED_TO_DRIVERS", "CANCELLED"],
  OFFERED_TO_DRIVERS: ["DRIVER_APPLIED", "CANCELLED"],
  DRIVER_APPLIED: ["DRIVER_SELECTED", "OFFERED_TO_DRIVERS", "CANCELLED"],
  DRIVER_SELECTED: ["SUPPLIER_CONFIRMED", "OFFERED_TO_DRIVERS", "CANCELLED"],
  SUPPLIER_CONFIRMED: ["SCHEDULED", "DRIVER_ASSIGNED", "CANCELLED", "DISPUTED"],
  SCHEDULED: ["DRIVER_ASSIGNED", "ARRIVING_AT_PICKUP", "CANCELLED", "DISPUTED"],
  DRIVER_ASSIGNED: ["ARRIVING_AT_PICKUP", "CANCELLED", "DISPUTED"],
  ARRIVING_AT_PICKUP: ["AT_PICKUP", "DISPUTED", "CANCELLED"],
  AT_PICKUP: ["LOADING", "DISPUTED", "CANCELLED"],
  LOADING: ["LOADED", "DISPUTED", "CANCELLED"],
  LOADED: ["IN_TRANSIT", "DISPUTED", "CANCELLED"],
  IN_TRANSIT: ["ARRIVING_AT_DESTINATION", "DISPUTED", "CANCELLED"],
  ARRIVING_AT_DESTINATION: ["AT_DESTINATION", "DISPUTED"],
  AT_DESTINATION: ["UNLOADING", "DISPUTED"],
  UNLOADING: ["DELIVERED", "DISPUTED"],
  DELIVERED: ["PROOF_SUBMITTED", "DISPUTED"],
  PROOF_SUBMITTED: ["CONFIRMED", "DISPUTED", "DELIVERED"],
  CONFIRMED: ["COMPLETED"],
  COMPLETED: [],
  CANCELLED: [],
  DISPUTED: ["OFFERED_TO_DRIVERS", "IN_TRANSIT", "CANCELLED", "COMPLETED"],
};

export const INVOICE_TRANSITIONS: Record<InvoiceStatus, InvoiceStatus[]> = {
  DRAFT: ["ISSUED", "CANCELLED"],
  ISSUED: ["SENT", "VOID", "OVERDUE", "PARTIALLY_PAID", "PAID"],
  SENT: ["PARTIALLY_PAID", "PAID", "OVERDUE", "VOID"],
  PARTIALLY_PAID: ["PAID", "OVERDUE", "VOID"],
  PAID: [],
  OVERDUE: ["PARTIALLY_PAID", "PAID", "VOID"],
  VOID: [],
  CANCELLED: [],
};

export const PAYMENT_TRANSITIONS: Record<PaymentStatus, PaymentStatus[]> = {
  PENDING: ["PROCESSING", "CANCELLED"],
  PROCESSING: ["COMPLETED", "FAILED", "CANCELLED"],
  COMPLETED: ["REFUNDED"],
  FAILED: ["PENDING", "CANCELLED"],
  REFUNDED: [],
  CANCELLED: [],
};

export const DISPUTE_TRANSITIONS: Record<DisputeStatus, DisputeStatus[]> = {
  OPEN: ["UNDER_REVIEW", "REJECTED", "CLOSED"],
  UNDER_REVIEW: ["WAITING_FOR_INFORMATION", "RESOLVED", "REJECTED"],
  WAITING_FOR_INFORMATION: ["UNDER_REVIEW", "RESOLVED", "REJECTED"],
  RESOLVED: ["CLOSED"],
  REJECTED: ["CLOSED"],
  CLOSED: [],
};

const JOB_RELEASE_STATUSES: TransportJobStatus[] = [
  "SUPPLIER_CONFIRMED",
  "SCHEDULED",
  "DRIVER_ASSIGNED",
  "ARRIVING_AT_PICKUP",
  "AT_PICKUP",
  "LOADING",
  "LOADED",
  "IN_TRANSIT",
  "ARRIVING_AT_DESTINATION",
  "AT_DESTINATION",
  "UNLOADING",
  "DELIVERED",
  "PROOF_SUBMITTED",
  "CONFIRMED",
  "COMPLETED",
];

export function detailsReleased(status: TransportJobStatus) {
  return JOB_RELEASE_STATUSES.includes(status);
}

export function canTransition<T extends string>(map: Record<T, T[]>, from: T, to: T) {
  return map[from]?.includes(to) ?? false;
}

export function assertTransition<T extends string>(map: Record<T, T[]>, from: T, to: T) {
  if (!canTransition(map, from, to)) {
    throw Errors.invalidTransition(from, to);
  }
}

export const DRIVER_FORWARD_STATUSES: TransportJobStatus[] = [
  "ARRIVING_AT_PICKUP",
  "AT_PICKUP",
  "LOADING",
  "LOADED",
  "IN_TRANSIT",
  "ARRIVING_AT_DESTINATION",
  "AT_DESTINATION",
  "UNLOADING",
  "DELIVERED",
];
